version: '3.7'
services:
  nginx:
    image: nginx:1.15.6
    ports:
      - "8080:80"
    environment:
    - NGINX_PORT=80
    volumes:
      - /opt/html:/usr/share/nginx/html
    networks:
      - default
  mysql-v8:
    # replace username/repo:tag with your name and image details
    image: mysql/mysql-server:8.0
    # container_name: mysql-v8
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "Wf3977696"
    volumes:
      - /opt/docker-data/mysql-datadir:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - default
      #myhost: {}
      #deploy:
      #mode: global
    # command: ["docker", "system", "prune", "-f"]
    #healthcheck:
    #test: ["docker", "system", "prune", "-f"]
      #test: echo ">>>>>>>>>>>>>>>"
      #  interval: 1m30s
      #timeout: 10s
      #retries: 3
      #start_period: 40s
      #networks:
      #myhost:
      #external: true
      #name: host
