version: '3.1'
services:
  mysql-v8:
    # replace username/repo:tag with your name and image details
    image: mysql/mysql-server:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "Wf3977696"
    volumes:
      - /opt/docker-data/mysql-datadir:/var/lib/mysql
    ports:
      - "3306:3306"
